### ISSUE TITLE
domain() works with only one domain.

### ISSUE THREAD

**Issue by winavin** [laravel/folio#128] opened 2023-12-17 10:11 UTC
### Folio Version

1.1.5

### Laravel Version

10.37.3

### PHP Version

8.1.4

### Description

```php
Folio::path(resource_path("views/pages/"));
Folio::domain('domain-one.test')->path(resource_path("views/pages/tenants/one"));
Folio::domain('domain-two.test')->path(resource_path("views/pages/tenants/two"));
```

First and 2nd line is working. but 2nd or any next domain is not working.
```php
foreach($domains as $domain)
{
Folio::domain($domain->domain)->path(resource_path("views/pages/tenants/$domain->slug"));
}
```

in above code only first domain is working. any next domains are not working

### Steps To Reproduce

in FolioServiceProvider

```php
public function boot(): void
    {
        Folio::path(resource_path("views/pages/"));
        Folio::domain('domain-one.test')->path(resource_path("views/pages/tenants/one"));
        Folio::domain('domain-two.test')->path(resource_path("views/pages/tenants/two"));
    }
```

**Comment by nunomaduro** [comment] 2023-12-19 10:24
Hey there,

I am unable to reproduce your issue. However, it seems that the first `Folio::path` line points to folders shared with the lines below, specifically `views/pages/tenants`.

Can you try something like this and let me know how it goes?

```
        Folio::path(resource_path("views/pages/something-else"));
        Folio::domain('domain-one.test')->path(resource_path("views/pages/tenants/one"));
        Folio::domain('domain-two.test')->path(resource_path("views/pages/tenants/two"));
```

**Comment by winavin** [comment] 2023-12-19 10:47
This is my folder structure.
![Screenshot 2023-12-19 160745](https://github.com/laravel/folio/assets/83947656/9dc62a85-7130-4cbf-87e7-16d5ae2cc4f4)

in FolioServiceProvider
```php
public function boot(): void
    {
        Folio::path(resource_path("views/pages/central"));
        Folio::domain('domain-one.test')->path(resource_path("views/pages/tenants/one"));
        Folio::domain('domain-two.test')->path(resource_path("views/pages/tenants/two"));
    }
```
Output for Folio Routes

php artisan folio:list
```

  GET       / .................................. resources/views/pages/central/index.blade.php  
  GET       domain-one.test/about-us ........... resources/views/pages/tenants/one/about-us.blade.php 
```
---------------------------------xxx------------------xxx----------------------
for
```php
public function boot(): void
    {
        Folio::path(resource_path("views/pages"));
        Folio::domain('domain-one.test')->path(resource_path("views/pages/tenants/one"));
        Folio::domain('domain-two.test')->path(resource_path("views/pages/tenants/two"));
    }
```
Output is
```
  GET       domain-one.test/ ................ resources/views/pages/tenants/one/index.blade.php  
  GET       domain-one.test/about-us ........ resources/views/pages/tenants/one/about-us.blade.php  
  GET       /central ........................ resources/views/pages/central/index.blade.php  
  GET       /tenants/one .................... resources/views/pages/tenants/one/index.blade.php  
  GET       /tenants/one/about-us ........... resources/views/pages/tenants/one/about-us.blade.php  
  GET       /tenants/two .................... resources/views/pages/tenants/two/index.blade.php  
  GET       /tenants/two/about-us ........... resources/views/pages/tenants/two/about-us.blade.php
```

**Comment by winavin** [comment] 2023-12-19 10:53
Just to clarify...
```php
 'providers' => ServiceProvider::defaultProviders()->merge([
        /*
         * Package Service Providers...
         */

        /*
         * Application Service Providers...
         */
        App\Providers\AppServiceProvider::class,
        App\Providers\AuthServiceProvider::class,
        // App\Providers\BroadcastServiceProvider::class,
        App\Providers\EventServiceProvider::class,
        App\Providers\RouteServiceProvider::class,
        App\Providers\FolioServiceProvider::class,
        
        /*
         * TenancyServiceProvider should be last provider
         */
        App\Providers\TenancyServiceProvider::class,

    ])->toArray(),
```

this is my Service Provider Sequence. is it because of TenancyServiceProvider::class ?

**Comment by winavin** [comment] 2023-12-19 11:19
It seems like when there are same folder structure for multiple domains, that same folder structure conflict with creating urls.
```
pages
- tenants
---tenant-one
----- index.blade.php [ showing ]
----- same-page-name-for-each-domain.blade.php [ showing ]
----- different-page-name-for-domain-one.blade.php [ showing ]
---tenant-two
----- index.blade.php [ not showing ]
----- same-page-name-for-each-domain.blade.php [ not showing ]
----- different-page-name-for-domain-two.blade.php [ showing ]
```
then

routes for index and same page is not showing for domain two and following domains. while, different page names or folder structure is registered for each domain.

**Comment by nunomaduro** [comment] 2023-12-19 14:07
Thanks for sharing that info. Do you mind of creating and sharing a GitHub link to a open-source repository with fresh Laravel application that I can clone to reproduce your issue?

**Comment by nunomaduro** [comment] 2023-12-19 14:11
Because it may take a while, please create an new issue with that link, and a reference to this issue. Going to close this issue meanwhile.

**Closed by nunomaduro** 2023-12-19 14:11 UTC
Labels: needs more info
